In [12]:
import numpy as np

## 기본

In [17]:
arr = np.array([1,2,3])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(3,)
1
3


## dype 설정

In [23]:
arr = np.array([[1,2,3], [1,2,3]])
print(arr.dtype)
arr2 = np.array([[1,2,3], [2,3,4]], dtype = np.uint8)
print(arr2.dtype)

int64
uint8


## reshape
* 동일한 size의 다른 shape의 행렬로 바꿔줌
* -1을 인자로 받을 경우 size / 앞에서 나온 shape 값이 들어감

In [34]:
arr = np.array([[1,2,3], [2,4,5]])
print(arr.reshape([3, 2]))
print(arr.reshape(6))
print(arr.reshape([6]))
print(arr.reshape([3, -1]))

[[1 2]
 [3 2]
 [4 5]]
[1 2 3 2 4 5]
[1 2 3 2 4 5]
[[1 2]
 [3 2]
 [4 5]]


## random array 생성

In [46]:
arr = np.random.randn(8,8)
print(arr)
print(arr.reshape(-1, 2, 2, 4))
print(arr.reshape(-1))


[[ 0.89907788 -0.8392467  -0.214755    0.39489996  0.38356881 -0.37030671
  -0.49797791 -0.37988108]
 [ 0.26418623  1.17092182 -0.85848649 -0.03988383 -0.71830159 -0.6612612
   0.64393279  0.37546246]
 [-1.51376933 -0.63820669  0.5890968  -4.59264826  1.32401449  0.98649571
   1.30485154 -0.81427736]
 [-0.29782593  0.78698549 -1.45826549  1.16855582  0.81565777  0.91860215
  -2.02876782 -0.94401478]
 [-0.29942474  1.62495451  1.30708407  1.26006389 -0.43280886 -0.56601483
   0.62777784  2.02682433]
 [-1.17181083  1.899081    0.26473722 -0.54492694 -2.41984049  1.90430957
  -0.22869189  1.42219678]
 [-0.32832985 -0.98593005  0.91185601  2.59639387 -1.39059231  0.77972525
  -0.53247655  0.3543493 ]
 [ 2.28149868 -1.63843458 -2.28022133  0.59732277 -1.35130276  0.02519353
  -0.88533045  1.44688389]]
[[[[ 0.89907788 -0.8392467  -0.214755    0.39489996]
   [ 0.38356881 -0.37030671 -0.49797791 -0.37988108]]

  [[ 0.26418623  1.17092182 -0.85848649 -0.03988383]
   [-0.71830159 -0.6612612   0.

## ravel
* 1차원의 행렬로 쭉 펴주는 함수
* reshape(-1)과 같음

In [51]:
arr = np.random.randn(4,4)
print(arr.ravel())
print(arr.reshape(-1))
arr.ravel() == arr.reshape(-1)

[-0.82023709 -0.1509569  -1.85907734  0.0520634   0.82477942 -1.03232021
  0.17397539 -1.53428038 -0.9555361  -1.80523221  1.66376897  0.16547716
 -1.18056366 -0.33596981 -1.0682005  -1.06816372]
[-0.82023709 -0.1509569  -1.85907734  0.0520634   0.82477942 -1.03232021
  0.17397539 -1.53428038 -0.9555361  -1.80523221  1.66376897  0.16547716
 -1.18056366 -0.33596981 -1.0682005  -1.06816372]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

## expand_dims
* 값은 유지한 채로 차원만 늘리는 함수

In [62]:
arr = np.random.randn(4,4,4)
print(arr)
print(np.expand_dims(arr, 1))
print(np.expand_dims(arr, -1))
print(np.expand_dims(arr, 0))

[[[ 1.70682197e+00 -6.41704847e-01  5.41843942e-01  3.02831769e-01]
  [ 1.29457319e+00 -1.19519185e-01  1.43333591e-02  1.27485202e+00]
  [-5.78180981e-01  1.07470918e-01 -2.31588055e+00  1.59497711e-01]
  [-4.42452867e-02 -2.07463126e+00  5.43320886e-01  3.26099245e-01]]

 [[ 5.74692534e-01 -9.86191158e-01  7.57000305e-01  7.40787755e-02]
  [ 8.26803571e-01  1.01817385e+00  5.34083233e-01  7.81645362e-01]
  [ 9.04097643e-01 -1.59645976e-01  1.15601381e+00 -2.73338138e-01]
  [ 1.29917310e+00  5.66433392e-01  9.49035442e-01 -7.38905878e-01]]

 [[-1.66056702e-03  8.18152214e-01  2.73165176e-01 -6.42793739e-01]
  [ 6.65711053e-01  1.25423656e+00  7.17759119e-01 -5.21250189e-02]
  [ 4.13622377e-01  1.10325119e+00 -1.01585522e+00 -6.37737033e-01]
  [ 5.82480511e-01 -8.74029189e-01  1.21482199e+00 -3.12560991e-01]]

 [[ 1.46446998e+00 -1.54535680e+00 -3.60348619e-02  7.16462178e-01]
  [-5.20677099e-01  9.16400408e-01  1.53755350e+00  1.05682952e+00]
  [-4.77902583e-01 -1.02676362e+00 -8.2811